### ISSUE TITLE
Beautify or prettify log messages

### ISSUE THREAD

**Issue by konard** [deep-foundation/deep-packages#132] opened 2024-07-15 18:48 UTC
Single log line is converted to formatted JSON.
From JSON we get formatted SQL/JavaScript and so on.

**Comment by mohmed-ahmed-dev** [comment] 2024-09-06 14:52
What is the ultimate goal of converting text logs to JSON format? (For example, data analysis, storage, visualization)
What benefits do you expect to gain from this conversion?
To clarify the difficulties you're facing:
What challenges are you encountering during the conversion process? (e.g., inconsistent log formats, missing fields, errors during conversion)
Are you receiving any specific error messages?
To identify the tools you're using:
What programming language or tools are you currently using to convert the logs? (e.g., Python, JavaScript, command-line tools)
Are you using any specific libraries or tools for the conversion process?

**Comment by ivansglazunov** [comment] 2024-09-12 13:07
> What is the ultimate goal of converting text logs to JSON format? (For example, data analysis, storage, visualization) What benefits do you expect to gain from this conversion? To clarify the difficulties you're facing: What challenges are you encountering during the conversion process? (e.g., inconsistent log formats, missing fields, errors during conversion) Are you receiving any specific error messages? To identify the tools you're using: What programming language or tools are you currently using to convert the logs? (e.g., Python, JavaScript, command-line tools) Are you using any specific libraries or tools for the conversion process?

We will soon add native support for remote debugging and debuggers. This is what will be intended for debugging convenience.
The results that are written now are not debugging, but literally what the code returns, and this is saved to the database. If the code fails with an error, the error is written as the content of the negative calculation result. These json are the input/output standard, not debug. A universal format was needed.
Different languages ​​need different debugging standards, something does not support them, but js, for example, can do it in https://github.com/node-inspector/node-inspector.
The task of adding a debugger is in the plans, not yet taken. Tentatively - October-December.

**Comment by ivansglazunov** [comment] 2024-09-12 13:07
The essence of the issue is incorrect.

**Closed as completed by ivansglazunov** 2024-09-12 13:07 UTC
Labels: enhancement, good first issue, help wanted
